export function createDefaultState() {
  return {
    campaign: {
      title: "The Saltwind Chapter",
      progress: 42,
      threat: 7,
      doom: 3,
      omen: 5,
      clues: 6,
      activeSceneId: "min-min-track",
      scenes: [
        {
          id: "station-road",
          title: "Station Road Omen",
          status: "cleared",
          progress: 100,
          summary: "A road train vanished after chasing pale lights off the highway.",
        },
        {
          id: "min-min-track",
          title: "Min Min Track",
          status: "active",
          progress: 55,
          summary: "The team trails impossible lights through salt flats and mulga scrub.",
        },
        {
          id: "bunyip-water",
          title: "Blackwater Billabong",
          status: "planned",
          progress: 0,
          summary: "Locals speak of something in the reeds that remembers names.",
        },
        {
          id: "quinkan-stone",
          title: "Quinkan Stone Mouth",
          status: "failed",
          progress: 20,
          summary: "A cave painting site now whispers back in familiar voices.",
        },
      ],
    },
    character: {
      name: "Mara Quinn",
      role: "Bush tracker and reluctant witness",
      notes: "",
      attributes: {
        ST: 10,
        DX: 11,
        IQ: 13,
        HT: 10,
        Will: 13,
        Per: 12,
      },
      skills: {
        Observation: 14,
        Survival: 13,
        Occultism: 12,
        Stealth: 11,
        Firearms: 11,
        FirstAid: 12,
      },
      traits: [
        "Night hearing honed by station work",
        "Knows old road legends across western Queensland",
        "Keeps a notebook of unnatural weather patterns",
        "Flinches at children singing in empty places",
      ],
      stress: 6,
      fatigue: 4,
      hp: 10,
      equipment: [
        { name: "Lee-Enfield carbine", slot: "Hands", notes: "Old station rifle, reliable in dry weather." },
        { name: "Canvas duster", slot: "Outerwear", notes: "Dust-stained and lined with notebook pockets." },
      ],
      inventory: [
        { name: "Water flask", notes: "Half full, tastes faintly metallic." },
        { name: "Field notebook", notes: "Packed with sketches of tracks and lights." },
        { name: "Tin ward tokens", notes: "Local charms traded at a roadhouse." },
      ],
    },
    party: [
      { name: "Mara Quinn", hp: 10, stress: 6, role: "Tracker" },
      { name: "Tom Wren", hp: 11, stress: 3, role: "Stockman" },
      { name: "Ellen Vale", hp: 9, stress: 8, role: "Schoolteacher Occultist" },
    ],
    log: [
      "A dust storm carried lantern light across the salt flats after moonrise.",
      "Tom found bootprints that stop at the edge of dry clay and do not return.",
      "A child in the last roadhouse drew the same red figure from three different dreams.",
    ],
    recentRolls: [
      {
        label: "Opening Observation",
        target: 14,
        roll: 11,
        outcome: "Success by 3",
      },
    ],
    lore: [
      {
        title: "Min Min Lights",
        type: "Entity",
        summary: "Cold lights that lure travelers into distance distortions and silence.",
      },
      {
        title: "Bunyip Water",
        type: "Location",
        summary: "A wetland pocket where sound travels badly and reflections arrive late.",
      },
      {
        title: "Quinkan Shade",
        type: "Entity",
        summary: "Stone-shadow intelligences that borrow memory and voice.",
      },
      {
        title: "Scrub Choir",
        type: "Phenomenon",
        summary: "Wind through spinifex that begins to mimic human breathing in rhythm.",
      },
    ],
    gm: {
      notes: "",
      players: [
        {
          id: "mara-quinn",
          name: "Mara Quinn",
          role: "Tracker",
          initiative: 12,
          hp: 10,
          maxHp: 10,
          stress: 6,
          st: 10,
          dx: 11,
          iq: 13,
          ht: 10,
          will: 13,
          per: 12,
          notes: "Lead investigator and primary witness to the lights.",
        },
        {
          id: "tom-wren",
          name: "Tom Wren",
          role: "Stockman",
          initiative: 11,
          hp: 11,
          maxHp: 11,
          stress: 3,
          st: 11,
          dx: 10,
          iq: 10,
          ht: 11,
          will: 10,
          per: 11,
          notes: "Reliable with routes, but spooks easily in open dark country.",
        },
        {
          id: "ellen-vale",
          name: "Ellen Vale",
          role: "Schoolteacher Occultist",
          initiative: 10,
          hp: 9,
          maxHp: 9,
          stress: 8,
          st: 9,
          dx: 10,
          iq: 12,
          ht: 9,
          will: 12,
          per: 11,
          notes: "Knows comparative folklore and pattern recognition rituals.",
        },
      ],
      initiativeCreatures: [],
      scenarios: [
        {
          id: "saltwind-chapter",
          title: "The Saltwind Chapter",
          objective: "Find the source of the Min Min lure and close its route before dawn.",
          act: "Act II",
          difficulty: "Hard",
          threat: "High",
          tags: ["lights", "outback", "investigation"],
          notes: "Use road isolation, dust glare, and conflicting witness accounts.",
        },
      ],
      encounters: [
        {
          id: "min-min-ambush",
          title: "Min Min Ambush",
          scenarioId: "saltwind-chapter",
          range: "Salt flats at night",
          threat: "Severe",
          difficulty: "Hard",
          creatureIds: ["quinkan-shade"],
          composition: "1 light swarm phenomenon, 1 separated witness, environmental panic",
          tactics: "Split line of sight, pull one investigator from cover, escalate omen on failed fright checks.",
          rewards: "Gain 2 clues and the road sketch if contained.",
        },
      ],
      creatures: [
        {
          id: "quinkan-shade",
          name: "Quinkan Shade",
          category: "Rock-shadow entity",
          difficulty: "Hard",
          tags: ["shadow", "rock-art", "fear"],
          st: 11,
          dx: 12,
          iq: 10,
          ht: 11,
          will: 13,
          per: 14,
          hp: 12,
          fp: 11,
          speed: 6.0,
          move: 7,
          dr: 2,
          attack: "Shadow rake",
          damage: "1d+2 cutting",
          traits: "Dark vision; voice mimicry; fright aura -2",
          notes: "Prefers echoing stone country and isolates targets before striking.",
        },
      ],
    },
  };
}
